/**
 * BGM bed orchestration (workbench hook, same deps-object pattern as use-clip-insert):
 *  - mount a music file (upload / generated bytes): blob src + sig + OPFS + cloud vault, auto level
 *    from measured loudness (bed sits BGM_AUTO_UNDER_DB below narration; skips silently to the
 *    default when measurement fails);
 *  - keep the engine's bed channel in sync with comp.bgm (speech spans from the transcripts →
 *    the same pure bgmGainAt closure preview and export share);
 *  - draft restore: revive a dead blob src from OPFS/cloud by sig (recoverLocalClips analog);
 *  - 响度统一: align every inserted clip's loudness to the main narration via per-shot volumeDb
 *    (attenuate-only; too-quiet sources are reported, not silently boosted);
 *  - generation: POST /api/studio/music → bytes → the same mount path as upload.
 */

import { useEffect, useRef, useState, type MutableRefObject, type SetStateAction } from 'react';
import {
  type BgmTrack,
  type Composition,
  type SpeechSpan,
  type VideoShot,
  bgmGainAt,
  mergeSpeechSpans,
  patchBgm,
  patchShotAudio,
  totalDuration,
} from '@pireel/studio-engine/composition';
import { mappedCaptionSegs } from '@pireel/studio-engine/captions-relay';
import type { AsrSegment } from '@pireel/studio-engine/build-blocks';
import { extractAudio } from '@pireel/studio-engine/video-edit/extract-audio';
import { studioProviders } from '@pireel/studio-engine/providers';
import { toast } from '@pireel/ui/toast';
import type { VideoTrackEngine } from './video-track-engine';
import { decodeAudioFile } from './export-audio-mix';
import { bgmAutoVolumeDb, matchLoudnessDb, measureBufferLoudnessDb, measureLoudnessDb } from './loudness';
import { fileSig } from './media';
import { loadLocalVideo, saveLocalVideo } from './local-media';
import { t } from './i18n';

export interface BgmDeps {
  comp: Composition;
  compRef: MutableRefObject<Composition>;
  setComp: (action: SetStateAction<Composition>) => void;
  videoFileRef: MutableRefObject<File | null>;
  videoSigRef: MutableRefObject<string | null>;
  clipFilesRef: MutableRefObject<Map<string, File>>;
  videoEngineRef: MutableRefObject<VideoTrackEngine | null>;
  asrRef: MutableRefObject<AsrSegment[] | null>;
  clipAsrRef: MutableRefObject<Record<string, AsrSegment[]>>;
  ensureShots: (c: Composition) => VideoShot[];
  pickFile: (accept: string) => Promise<File | null>;
  backupMediaToCloud: (file: File, sig: string, kind: 'video' | 'clip') => void;
  pushUndoSnapshot: () => void;
}

export function useBgm(deps: BgmDeps) {
  const { comp, compRef, setComp, videoFileRef, videoSigRef, clipFilesRef, videoEngineRef, asrRef, clipAsrRef, ensureShots, pickFile, backupMediaToCloud, pushUndoSnapshot } = deps;
  const bgmFileRef = useRef<File | null>(null);
  const [bgmFileRev, setBgmFileRev] = useState(0);
  const [generating, setGenerating] = useState(false);
  const [normalizing, setNormalizing] = useState(false);
  const [normalizeNote, setNormalizeNote] = useState<string | null>(null);
  /** Main-narration loudness cache (extract+decode is seconds on long videos — measure once per source). */
  const narrDbRef = useRef<{ sig: string; db: number | null } | null>(null);
  const recoverTriedRef = useRef<string | null>(null);

  /** MERGED speech windows on the edited timeline (ducking mask; [] until transcripts exist). */
  const speechSpans = (): SpeechSpan[] => {
    const c = compRef.current;
    const groups = mappedCaptionSegs(ensureShots(c), asrRef.current, clipAsrRef.current ?? {});
    return mergeSpeechSpans(groups.map((g) => ({ start: g.start, end: g.end })));
  };

  const narrationDb = async (): Promise<number | null> => {
    const f = videoFileRef.current;
    if (!f) return null;
    const sig = videoSigRef.current ?? fileSig(f);
    if (narrDbRef.current?.sig === sig) return narrDbRef.current.db;
    let db: number | null = null;
    try {
      db = await measureLoudnessDb(await extractAudio(f));
    } catch {
      /* no audio track / decode failure → default bed level */
    }
    narrDbRef.current = { sig, db };
    return db;
  };

  /** Mount music bytes as the bed: measure → auto level → OPFS + cloud → comp.bgm.
   *  opts.startSec = drop position on the music lane (absent = bed from 0). */
  const mountBgmFile = async (file: File, label?: string, opts?: { startSec?: number }) => {
    let durationSec: number | undefined;
    let volumeDb: number | undefined;
    try {
      const buf = await decodeAudioFile(file);
      durationSec = Math.round(buf.duration * 10) / 10;
      const bgmDb = measureBufferLoudnessDb(buf);
      const narrDb = await narrationDb();
      if (bgmDb != null && narrDb != null) volumeDb = bgmAutoVolumeDb(narrDb, bgmDb);
    } catch {
      toast.error(t('workbench.musicDecodeFailed'));
      return;
    }
    const sig = fileSig(file);
    const url = URL.createObjectURL(file);
    bgmFileRef.current = file;
    setBgmFileRev((v) => v + 1);
    void saveLocalVideo(file, sig); // the OPFS library is byte-agnostic despite the name
    backupMediaToCloud(file, sig, 'clip'); // sig→key record rides the clips slot (content-addressed vault is type-agnostic)
    pushUndoSnapshot();
    const startSec = opts?.startSec != null && opts.startSec > 0.05 ? Math.round(opts.startSec * 10) / 10 : undefined;
    setComp((c) => ({
      ...c,
      bgm: {
        src: url,
        sig,
        label: label ?? file.name.replace(/\.[a-z0-9]+$/i, ''),
        ...(durationSec != null ? { durationSec } : {}),
        ...(volumeDb != null && volumeDb !== 0 ? { volumeDb } : {}),
        ...(startSec != null ? { startSec } : {}),
      },
    }));
  };

  /** Mount from an asset URL (assets-panel "use as BGM" / timeline drop): fetch bytes through the
   *  same-origin proxy, then the exact upload path (loudness auto-level included). */
  const mountBgmFromUrl = async (url: string, label?: string, opts?: { startSec?: number }) => {
    const r = await fetch(`/api/media/fetch?url=${encodeURIComponent(url)}`);
    if (!r.ok) {
      toast.error(t('workbench.musicGenFailed'));
      return;
    }
    const type = r.headers.get('content-type')?.split(';')[0] || 'audio/mpeg';
    const name = (() => {
      try {
        return decodeURIComponent(new URL(url).pathname.split('/').pop() || '') || 'bgm';
      } catch {
        return 'bgm';
      }
    })();
    await mountBgmFile(new File([await r.blob()], name, { type }), label, opts);
  };

  const uploadBgm = async () => {
    const f = await pickFile('audio/*');
    if (!f) return;
    await mountBgmFile(f);
    // Audio CONTENT lives in the assets library (classification: content vs settings) — register the
    // upload there too, best-effort: the bed already works from local bytes if this fails.
    void (async () => {
      try {
        const { url } = await studioProviders().uploads.upload(f, { contentType: f.type || 'audio/mpeg', filename: f.name });
        await fetch('/api/me/uploads', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ kind: 'audio', url, label: f.name, role: 'general', mime: f.type, byte_size: f.size }),
        });
      } catch {
        /* asset registration is a bonus, not a dependency */
      }
    })();
  };

  const removeBgm = () => {
    pushUndoSnapshot();
    bgmFileRef.current = null;
    setBgmFileRev((v) => v + 1);
    setComp((c) => {
      const { bgm: _drop, ...rest } = c;
      return rest as Composition;
    });
  };

  const patchBed = (patch: Partial<Pick<BgmTrack, 'volumeDb' | 'duck' | 'loop' | 'startSec'>>) => {
    setComp((c) => (c.bgm ? { ...c, bgm: patchBgm(c.bgm, patch) } : c));
  };

  /** Engine bed spec from current state; volume override feeds the slider's live preview. */
  const engineSpec = (bgm: BgmTrack, dbOverride?: number) => {
    const total = totalDuration(compRef.current);
    const spans = speechSpans();
    const b = dbOverride != null ? { ...bgm, volumeDb: dbOverride } : bgm;
    return {
      url: bgm.src,
      durationSec: bgm.durationSec,
      loop: bgm.loop !== false,
      offsetSec: bgm.offsetSec ?? 0,
      startSec: bgm.startSec ?? 0,
      gainAt: (tt: number) => bgmGainAt(b, tt, total, spans),
    };
  };

  const previewBedVolume = (db: number) => {
    const bgm = compRef.current.bgm;
    if (bgm) videoEngineRef.current?.setBgm(engineSpec(bgm, db));
  };

  // Engine sync: respec on any bed/timeline/bytes change (same-url respec swaps only the closure — no reload).
  const bgmUsable = !!comp.bgm && (bgmFileRef.current != null || !comp.bgm.src.startsWith('blob:'));
  useEffect(() => {
    const eng = videoEngineRef.current;
    if (!eng) return;
    const bgm = comp.bgm;
    if (!bgm || !bgmUsable) {
      eng.setBgm(null);
      return;
    }
    eng.setBgm(engineSpec(bgm));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comp.bgm, comp.shots, comp.video, bgmFileRev, bgmUsable]);

  // Draft restore: dead blob src + sig → OPFS, then cloud vault; remap to a fresh blob URL.
  useEffect(() => {
    const bgm = comp.bgm;
    if (!bgm?.sig || bgmFileRef.current || !bgm.src.startsWith('blob:')) return;
    if (recoverTriedRef.current === bgm.sig) return;
    recoverTriedRef.current = bgm.sig;
    void (async () => {
      let f = await loadLocalVideo(bgm.sig!);
      if (!f) f = await studioProviders().vault.fetch(bgm.sig!);
      if (!f) return; // stays fileMissing → panel offers reconnect
      void saveLocalVideo(f, bgm.sig!);
      bgmFileRef.current = f;
      setBgmFileRev((v) => v + 1);
      const url = URL.createObjectURL(f);
      setComp((c) => (c.bgm?.sig === bgm.sig ? { ...c, bgm: { ...c.bgm, src: url } } : c));
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comp.bgm?.sig, comp.bgm?.src]);

  /** Export payload (bytes + duck mask); null = no bed or bytes missing (export proceeds without it). */
  const bgmForExport = (): { file: File; speech: SpeechSpan[] } | null => {
    if (!compRef.current.bgm || !bgmFileRef.current) return null;
    return { file: bgmFileRef.current, speech: speechSpans() };
  };

  /** 响度统一: measure main + every inserted source, attenuate louder-than-main inserts via per-shot volumeDb. */
  const normalizeLoudness = async () => {
    if (normalizing) return;
    setNormalizing(true);
    setNormalizeNote(null);
    try {
      const mainDb = await narrationDb();
      if (mainDb == null) {
        setNormalizeNote(t('workbench.loudnessMainUnmeasurable'));
        return;
      }
      const shots = ensureShots(compRef.current);
      const srcs = [...new Set(shots.filter((s) => s.src).map((s) => s.src!))];
      let adjusted = 0;
      let quieter = 0;
      const perSrc = new Map<string, number>();
      for (const src of srcs) {
        const f = clipFilesRef.current.get(src);
        if (!f) continue;
        let db: number | null = null;
        try {
          db = await measureLoudnessDb(await extractAudio(f));
        } catch {
          /* clip without audio → skip */
        }
        if (db == null) continue;
        const match = matchLoudnessDb(mainDb, db);
        if (match == null) {
          if (db < mainDb - 3) quieter++;
          continue;
        }
        perSrc.set(src, match);
        adjusted++;
      }
      if (perSrc.size) {
        pushUndoSnapshot();
        setComp((c) => ({
          ...c,
          shots: (c.shots ?? []).map((s) => (s.src && perSrc.has(s.src) ? patchShotAudio(s, { volumeDb: perSrc.get(s.src)! }) : s)),
        }));
      }
      setNormalizeNote(
        quieter
          ? t('workbench.loudnessUnifiedWithQuiet', { n: adjusted, m: quieter })
          : t('workbench.loudnessUnified', { n: adjusted }),
      );
    } finally {
      setNormalizing(false);
    }
  };

  /** Hosted music generation → bytes → the same mount path as upload. */
  const generateBgm = async (prompt: string, durationSec: number) => {
    if (generating) return;
    setGenerating(true);
    try {
      const r = await fetch('/api/studio/music', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ prompt, duration_sec: durationSec }),
      });
      if (!r.ok) {
        const msg = (await r.json().catch(() => null)) as { error?: string } | null;
        toast.error(msg?.error || t('workbench.musicGenFailed'));
        return;
      }
      const { url } = (await r.json()) as { url: string };
      const bytes = await fetch(`/api/media/fetch?url=${encodeURIComponent(url)}`);
      if (!bytes.ok) {
        toast.error(t('workbench.musicGenFailed'));
        return;
      }
      const type = bytes.headers.get('content-type')?.split(';')[0] || 'audio/mpeg';
      const ext = /wav/.test(type) ? 'wav' : /mp4|m4a|aac/.test(type) ? 'm4a' : 'mp3';
      const file = new File([await bytes.blob()], `bgm.${ext}`, { type });
      await mountBgmFile(file, prompt.slice(0, 24));
    } finally {
      setGenerating(false);
    }
  };

  return {
    bgmFileRef,
    bgmUsable,
    uploadBgm,
    removeBgm,
    patchBed,
    previewBedVolume,
    bgmForExport,
    speechSpans,
    mountBgmFile,
    mountBgmFromUrl,
    normalizeLoudness,
    normalizing,
    normalizeNote,
    generateBgm,
    generating,
  };
}
